import express from "express";
import crypto from "crypto";
import {readFile} from "fs/promises";
import {WebSocketServer} from "ws";
import {Pool} from "pg";
import http from "http";

const app=express(),server=http.createServer(app),wss=new WebSocketServer({server});
const PORT=process.env.PORT||10000,CLIENT_ID=process.env.KICK_CLIENT_ID||"",CLIENT_SECRET=process.env.KICK_CLIENT_SECRET||"",BASE=(process.env.PUBLIC_URL||"").replace(/\/$/,""),LEGACY_OWNER=(process.env.KICK_CHANNEL||"lestarwolf").toLowerCase().replace(/[^a-z0-9]/g,""),DATABASE_URL=process.env.DATABASE_URL||"",COOKIE_SECRET=process.env.SESSION_SECRET||CLIENT_SECRET||crypto.randomBytes(32).toString("hex"),TOKEN_SECRET=process.env.TOKEN_ENCRYPTION_KEY||CLIENT_SECRET||COOKIE_SECRET,IS_PROD=process.env.NODE_ENV==="production";
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,ssl:process.env.PGSSLMODE==="disable"?false:{rejectUnauthorized:false}}):null;
const memoryStreamers=new Map(),memoryProgress=new Map(),seenMessages=new Set(),oauthStates=new Map(),rooms=new Map(),runtimes=new Map();
const EVENTS=["chat.message.sent","channel.subscription.gifts","channel.subscription.new","channel.subscription.renewal","kicks.gifted","livestream.status.updated"];
const BOSS_WINDOW=30*60*1000,BOSS_DURATION=90*1000,SQUIRREL_DURATION=15*1000,SKUNK_DURATION=15*1000;
const KICK_PUBLIC_KEY=`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq/+l1WnlRrGSolDMA+A8
6rAhMbQGmQ2SapVcGM3zq8ANXjnhDWocMqfWcTd95btDydITa10kDvHzw9WQOqp2
MZI7ZyrfzJuz5nhTPCiJwTwnEtWft7nV14BYRDHvlfqPUaZ+1KR4OCaO/wWIk/rQ
L/TjY0M70gse8rlBkbo2a8rKhu69RQTRsoaf4DVhDPEeSeI5jVrRDGAMGL3cGuyY
6CLKGdjVEM78g3JfYOvDU/RvfqD7L89TZ3iN94jrmWdGz34JNlEI5hqK8dd7C5EF
BEbZ5jgB8s8ReQV8H+MkuffjdAj3ajDDX3DOJMIut1lBrUVD1AaSrGCKHooWoL2e
twIDAQAB
-----END PUBLIC KEY-----`;

const b64=b=>Buffer.from(b).toString("base64url"),normalize=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]/g,""),safe=s=>String(s||"").replace(/[<>&"']/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;","'":"&#39;"})[c]);
const jsonForHtml=value=>JSON.stringify(value).replace(/</g,"\\u003c").replace(/-->/g,"--\\u003e");
function parseCookies(req){return Object.fromEntries(String(req.headers.cookie||"").split(";").map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf("=");return[decodeURIComponent(i<0?x:x.slice(0,i)),decodeURIComponent(i<0?"":x.slice(i+1))]}))}
function signed(value){const payload=b64(JSON.stringify(value)),sig=crypto.createHmac("sha256",COOKIE_SECRET).update(payload).digest("base64url");return`${payload}.${sig}`}
function unsigned(value){try{const [payload,sig]=String(value||"").split("."),expected=crypto.createHmac("sha256",COOKIE_SECRET).update(payload).digest(),actual=Buffer.from(sig||"","base64url");if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return null;return JSON.parse(Buffer.from(payload,"base64url").toString())}catch{return null}}
function cookie(res,name,value,maxAge=60*60*24*30){res.setHeader("Set-Cookie",`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${IS_PROD?"; Secure":""}`)}
function key32(){return crypto.createHash("sha256").update(TOKEN_SECRET).digest()}
function encrypt(text){if(!text)return"";const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",key32(),iv),body=Buffer.concat([cipher.update(String(text),"utf8"),cipher.final()]),tag=cipher.getAuthTag();return`${b64(iv)}.${b64(tag)}.${b64(body)}`}
function decrypt(value){if(!value)return"";try{const [iv,tag,body]=String(value).split(".").map(x=>Buffer.from(x,"base64url")),decipher=crypto.createDecipheriv("aes-256-gcm",key32(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(body),decipher.final()]).toString()}catch{return""}}
const newOverlayKey=()=>crypto.randomBytes(24).toString("base64url");

async function initDb(){if(!pool)return;await pool.query(`
  CREATE TABLE IF NOT EXISTS streamers(
    kick_user_id TEXT PRIMARY KEY, username TEXT NOT NULL, display_name TEXT NOT NULL,
    avatar_url TEXT NOT NULL DEFAULT '', overlay_key TEXT UNIQUE NOT NULL,
    access_token_enc TEXT NOT NULL DEFAULT '', refresh_token_enc TEXT NOT NULL DEFAULT '',
    token_expires_at BIGINT NOT NULL DEFAULT 0, subscription_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS viewer_progress(
    streamer_id TEXT PRIMARY KEY REFERENCES streamers(kick_user_id) ON DELETE CASCADE,
    data JSONB NOT NULL DEFAULT '{}'::jsonb, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS webhook_messages(
    message_id TEXT PRIMARY KEY, received_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  CREATE INDEX IF NOT EXISTS streamers_overlay_key_idx ON streamers(overlay_key);
  CREATE INDEX IF NOT EXISTS streamers_username_idx ON streamers(username);
`)}
function normalizeStreamer(row){return row?{kickUserId:String(row.kick_user_id),username:row.username,displayName:row.display_name,avatarUrl:row.avatar_url,overlayKey:row.overlay_key,accessTokenEnc:row.access_token_enc,refreshTokenEnc:row.refresh_token_enc,tokenExpiresAt:Number(row.token_expires_at)||0,subscriptionData:row.subscription_data||{}}:null}
async function getStreamerById(id){id=String(id||"");if(!id)return null;if(pool)return normalizeStreamer((await pool.query("SELECT * FROM streamers WHERE kick_user_id=$1",[id])).rows[0]);return memoryStreamers.get(id)||null}
async function getStreamerByKey(key){if(!key)return null;if(pool)return normalizeStreamer((await pool.query("SELECT * FROM streamers WHERE overlay_key=$1",[key])).rows[0]);return[...memoryStreamers.values()].find(x=>x.overlayKey===key)||null}
async function getStreamerByUsername(username){username=normalize(username);if(!username)return null;if(pool)return normalizeStreamer((await pool.query("SELECT * FROM streamers WHERE username=$1",[username])).rows[0]);return[...memoryStreamers.values()].find(x=>x.username===username)||null}
async function saveStreamer(input){const current=await getStreamerById(input.kickUserId),record={...current,...input,overlayKey:current?.overlayKey||input.overlayKey||newOverlayKey()};if(pool){const r=await pool.query(`INSERT INTO streamers(kick_user_id,username,display_name,avatar_url,overlay_key,access_token_enc,refresh_token_enc,token_expires_at,subscription_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT(kick_user_id) DO UPDATE SET username=EXCLUDED.username,display_name=EXCLUDED.display_name,avatar_url=EXCLUDED.avatar_url,access_token_enc=EXCLUDED.access_token_enc,refresh_token_enc=CASE WHEN EXCLUDED.refresh_token_enc='' THEN streamers.refresh_token_enc ELSE EXCLUDED.refresh_token_enc END,token_expires_at=EXCLUDED.token_expires_at,subscription_data=EXCLUDED.subscription_data,updated_at=NOW() RETURNING *`,[record.kickUserId,record.username,record.displayName,record.avatarUrl,record.overlayKey,record.accessTokenEnc||"",record.refreshTokenEnc||"",record.tokenExpiresAt||0,JSON.stringify(record.subscriptionData||{})]);return normalizeStreamer(r.rows[0])}memoryStreamers.set(record.kickUserId,record);return record}
async function updateTokens(streamer,tokens){return saveStreamer({...streamer,accessTokenEnc:encrypt(tokens.access_token),refreshTokenEnc:tokens.refresh_token?encrypt(tokens.refresh_token):streamer.refreshTokenEnc,tokenExpiresAt:Date.now()+(Number(tokens.expires_in)||3600)*1000})}
async function replaceOverlayKey(streamer){const fresh=newOverlayKey();if(pool){const r=await pool.query("UPDATE streamers SET overlay_key=$1,updated_at=NOW() WHERE kick_user_id=$2 RETURNING *",[fresh,streamer.kickUserId]);return normalizeStreamer(r.rows[0])}streamer.overlayKey=fresh;memoryStreamers.set(streamer.kickUserId,streamer);return streamer}
async function getProgress(streamerId){if(pool)return (await pool.query("SELECT data FROM viewer_progress WHERE streamer_id=$1",[streamerId])).rows[0]?.data||{};return memoryProgress.get(String(streamerId))||{}}
async function saveViewerProgress(streamerId,data){if(pool){await pool.query("INSERT INTO viewer_progress(streamer_id,data) VALUES($1,$2::jsonb) ON CONFLICT(streamer_id) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()",[streamerId,JSON.stringify(data)]);return}memoryProgress.set(String(streamerId),data)}
async function markMessage(id){if(!id)return true;if(pool){const r=await pool.query("INSERT INTO webhook_messages(message_id) VALUES($1) ON CONFLICT DO NOTHING RETURNING message_id",[id]);return!!r.rowCount}if(seenMessages.has(id))return false;seenMessages.add(id);if(seenMessages.size>5000)seenMessages.delete(seenMessages.values().next().value);return true}

function roomClients(key="legacy"){if(!rooms.has(key))rooms.set(key,new Set());return rooms.get(key)}
function send(key,event){const data=JSON.stringify(event);for(const ws of roomClients(key))if(ws.readyState===1)ws.send(data)}
function runtime(key){if(!runtimes.has(key))runtimes.set(key,{live:false,bossTimers:[],bossWindowTimer:0,bossUntil:0,squirrelTimer:0,squirrelUntil:0,skunkTimer:0,skunkUntil:0});return runtimes.get(key)}
function clearBoss(r){r.bossTimers.forEach(clearTimeout);r.bossTimers=[];clearTimeout(r.bossWindowTimer);r.bossWindowTimer=0}
function clearSquirrel(r){clearTimeout(r.squirrelTimer);r.squirrelTimer=0}
function clearSkunk(r){clearTimeout(r.skunkTimer);r.skunkTimer=0}
function scheduleBoss(key){const r=runtime(key);clearBoss(r);if(!r.live)return;const launch=()=>{if(r.live&&Date.now()>=r.bossUntil&&Date.now()>=r.squirrelUntil&&Date.now()>=r.skunkUntil){r.bossUntil=Date.now()+BOSS_DURATION;send(key,{type:"boss",hp:500,duration:BOSS_DURATION})}};r.bossTimers=[setTimeout(launch,(4+Math.random()*9)*60000),setTimeout(launch,(17+Math.random()*9)*60000)];r.bossWindowTimer=setTimeout(()=>scheduleBoss(key),BOSS_WINDOW)}
function scheduleSquirrel(key){const r=runtime(key);clearSquirrel(r);if(!r.live)return;r.squirrelTimer=setTimeout(()=>{if(r.live&&Date.now()>=r.bossUntil&&Date.now()>=r.squirrelUntil&&Date.now()>=r.skunkUntil){r.squirrelUntil=Date.now()+SQUIRREL_DURATION;send(key,{type:"squirrel",duration:SQUIRREL_DURATION})}scheduleSquirrel(key)},(8+Math.random()*8)*60000)}
function scheduleSkunk(key){const r=runtime(key);clearSkunk(r);if(!r.live)return;r.skunkTimer=setTimeout(()=>{if(r.live&&Date.now()>=r.bossUntil&&Date.now()>=r.squirrelUntil&&Date.now()>=r.skunkUntil){r.skunkUntil=Date.now()+SKUNK_DURATION;send(key,{type:"skunk",duration:SKUNK_DURATION})}scheduleSkunk(key)},(12+Math.random()*10)*60000)}
function setLive(key,live){const r=runtime(key);live=!!live;if(r.live===live)return;r.live=live;if(live){scheduleBoss(key);scheduleSquirrel(key);scheduleSkunk(key)}else{clearBoss(r);clearSquirrel(r);clearSkunk(r);r.bossUntil=r.squirrelUntil=r.skunkUntil=0;send(key,{type:"bossStop"});send(key,{type:"squirrelStop"});send(key,{type:"skunkStop"})}}

async function exchangeCode(code,verifier){const body=new URLSearchParams({grant_type:"authorization_code",client_id:CLIENT_ID,client_secret:CLIENT_SECRET,code,redirect_uri:BASE+"/callback",code_verifier:verifier}),r=await fetch("https://id.kick.com/oauth/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}),data=await r.json();if(!r.ok)throw Error(data.message||data.error||"Kick token exchange failed");return data}
async function refreshToken(streamer){const refresh=decrypt(streamer.refreshTokenEnc);if(!refresh)throw Error("Kick reconnect required");const body=new URLSearchParams({grant_type:"refresh_token",client_id:CLIENT_ID,client_secret:CLIENT_SECRET,refresh_token:refresh}),r=await fetch("https://id.kick.com/oauth/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}),data=await r.json();if(!r.ok)throw Error("Kick token refresh failed");return updateTokens(streamer,data)}
async function accessToken(streamer){if(streamer.tokenExpiresAt>Date.now()+60000)return decrypt(streamer.accessTokenEnc);streamer=await refreshToken(streamer);return decrypt(streamer.accessTokenEnc)}
async function kickUser(token){const r=await fetch("https://api.kick.com/public/v1/users",{headers:{Authorization:`Bearer ${token}`}}),data=await r.json();if(!r.ok)throw Error(data.message||"Could not read Kick user");const user=Array.isArray(data.data)?data.data[0]:data.data||data;return{kickUserId:String(user.user_id||user.id||""),username:normalize(user.username||user.name||user.channel_slug),displayName:user.username||user.name||user.channel_slug||"Kick Streamer",avatarUrl:typeof user.profile_picture==="string"?user.profile_picture:user.profile_picture?.url||""}}
async function subscribe(streamer,token){const r=await fetch("https://api.kick.com/public/v1/events/subscriptions",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({method:"webhook",events:EVENTS.map(name=>({name,version:1}))})}),text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}if(!r.ok)throw Error(data.message||`Kick event subscription failed (${r.status})`);return data}
function sessionStreamer(req){const s=unsigned(parseCookies(req).pack_session);return s&&Date.now()-s.iat<31*24*60*60*1000?String(s.id):""}
async function requireStreamer(req,res,next){try{const id=sessionStreamer(req);if(!id)return res.redirect("/?login=required");const streamer=await getStreamerById(id);if(!streamer)return res.redirect("/?login=required");req.streamer=streamer;next()}catch(e){next(e)}}
function verifyWebhook(req,raw){if(process.env.KICK_VERIFY_WEBHOOKS==="false")return true;const id=req.get("Kick-Event-Message-Id")||"",ts=req.get("Kick-Event-Message-Timestamp")||"",sig=req.get("Kick-Event-Signature")||"";if(!id||!ts||!sig)return!IS_PROD;try{return crypto.verify("RSA-SHA256",Buffer.from(`${id}.${ts}.${raw}`),KICK_PUBLIC_KEY,Buffer.from(sig,"base64"))}catch{return false}}

function landing(){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cyber Pack Wolf Game</title><link rel="stylesheet" href="/portal.css"></head><body><main class="hero"><div class="moon"></div><p class="eyebrow">KICK CHAT-CONTROLLED OBS GAME</p><h1>CYBER PACK<br><span>WOLF GAME</span></h1><p class="lead">Give every viewer a persistent wolf that levels up, earns loot, fights bosses, joins events and battles in PvP—all controlled from Kick chat.</p><div class="actions"><a class="primary" href="/connect">CONNECT WITH KICK</a><a class="secondary" href="/overlay/?demo=1">VIEW DEMO</a></div><p class="fine">Connect once, copy your private Browser Source URL, and start streaming.</p></main><section class="features"><article><b>🐺</b><h2>Persistent Wolves</h2><p>Levels, ranks, treats, cosmetics and records stay with each community.</p></article><article><b>⚔️</b><h2>Chat Events</h2><p>Bosses, moon drops, squirrel chases, skunks, PvP and pack jobs.</p></article><article><b>🎥</b><h2>OBS Ready</h2><p>One private 1920×1080 browser URL. No viewer download required.</p></article></section></body></html>`}
function dashboard(streamer){const url=`${BASE}/overlay/${streamer.overlayKey}`,commands=`${BASE}/commands/${encodeURIComponent(streamer.username)}`;return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safe(streamer.displayName)} · Cyber Pack</title><link rel="stylesheet" href="/portal.css"></head><body><main class="dash"><header><div><p class="eyebrow">CYBER PACK CONTROL DEN</p><h1>${safe(streamer.displayName)}</h1><p class="connected">● KICK CONNECTED</p></div>${streamer.avatarUrl?`<img class="profile" src="${safe(streamer.avatarUrl)}" alt="">`:""}</header><section class="card"><h2>Your private OBS Browser Source</h2><div class="urlrow"><input id="overlayUrl" readonly value="${safe(url)}"><button onclick="navigator.clipboard.writeText(overlayUrl.value);this.textContent='COPIED!'">COPY URL</button></div><p>Add it to OBS as a Browser Source at <b>1920 × 1080</b>. Keep this URL private.</p><a href="${safe(url)}?demo=1" target="_blank">Open overlay preview</a> · <a href="${safe(commands)}" target="_blank">Open command page</a></section><section class="card"><h2>Test the game</h2><div class="tests">${["wolf","pack","moon","boss","squirrel","skunk","pvp"].map(x=>`<button onclick="testGame('${x}',this)">TEST ${x.toUpperCase()}</button>`).join("")}</div><p id="testStatus"></p></section><section class="card danger"><h2>Security</h2><p>If your private OBS URL is shared, generate a new one. The old URL will stop working.</p><form method="post" action="/api/regenerate-key" onsubmit="return confirm('Replace your OBS URL? You must update OBS afterward.')"><button>GENERATE NEW PRIVATE URL</button></form></section></main><script>async function testGame(kind,button){button.disabled=true;const r=await fetch('/api/test/'+kind,{method:'POST'});document.getElementById('testStatus').textContent=r.ok?'Test sent to the overlay. Open the preview or OBS to see it.':'Test failed. Refresh and reconnect Kick.';setTimeout(()=>button.disabled=false,900)}</script></body></html>`}
function commandsPage(streamer){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safe(streamer.displayName)} Wolf Commands</title><link rel="stylesheet" href="/portal.css"></head><body><main class="dash commands"><p class="eyebrow">${safe(streamer.displayName)}'S CYBER PACK</p><h1>WOLF COMMANDS</h1>${[["FUN","!howl · !sit · !sleep · !treat · !dig · !zoomies · !boop @viewer · !play @viewer · !stats"],["PVP","!duel @viewer · !accept · !decline · !record · !fighters"],["EVENTS","!chase · !run"],["BOSS","!bite · !pounce · !special · !dodge · !protect @viewer · !howl"],["JOBS","!hunt · !scout · !guard · !forage"],["SHOP","!shop · !treats · !buy ITEM · !equip ITEM · !inventory · !unequip"]].map(([h,c])=>`<section class="card"><h2>${h}</h2><p>${c}</p></section>`).join("")}</main></body></html>`}

app.disable("x-powered-by");
app.get("/portal.css",async(req,res,next)=>{try{res.type("css").send(await readFile(new URL("./public/portal.css",import.meta.url),"utf8"))}catch(e){next(e)}});
app.get("/",(_,res)=>res.send(landing()));
app.get("/health",(_,res)=>res.json({ok:true,version:"4.0.0",database:!!pool,rooms:rooms.size}));
app.get("/connect",(req,res)=>{if(!CLIENT_ID||!CLIENT_SECRET||!BASE)return res.status(503).send("Kick connection is not configured yet.");const verifier=b64(crypto.randomBytes(48)),challenge=crypto.createHash("sha256").update(verifier).digest("base64url"),state=b64(crypto.randomBytes(18));oauthStates.set(state,{verifier,created:Date.now()});setTimeout(()=>oauthStates.delete(state),10*60*1000);const q=new URLSearchParams({response_type:"code",client_id:CLIENT_ID,redirect_uri:BASE+"/callback",scope:"events:subscribe user:read channel:read kicks:read",code_challenge:challenge,code_challenge_method:"S256",state});res.redirect("https://id.kick.com/oauth/authorize?"+q)});
app.get("/setup",(_,res)=>res.redirect("/connect"));
app.get("/callback",async(req,res,next)=>{try{const pending=oauthStates.get(String(req.query.state||""));oauthStates.delete(String(req.query.state||""));if(!pending||Date.now()-pending.created>10*60*1000)throw Error("Kick sign-in expired. Please try again.");const tokens=await exchangeCode(String(req.query.code||""),pending.verifier),user=await kickUser(tokens.access_token);if(!user.kickUserId||!user.username)throw Error("Kick did not return a valid streamer account.");let streamer=await saveStreamer({...user,overlayKey:newOverlayKey(),accessTokenEnc:encrypt(tokens.access_token),refreshTokenEnc:encrypt(tokens.refresh_token||""),tokenExpiresAt:Date.now()+(Number(tokens.expires_in)||3600)*1000,subscriptionData:{}});const subscriptions=await subscribe(streamer,tokens.access_token);streamer=await saveStreamer({...streamer,subscriptionData:subscriptions});cookie(res,"pack_session",signed({id:streamer.kickUserId,iat:Date.now()}));res.redirect("/dashboard?connected=1")}catch(e){next(e)}});
app.get("/dashboard",requireStreamer,(req,res)=>res.send(dashboard(req.streamer)));
app.get("/commands/:username",async(req,res,next)=>{try{const streamer=await getStreamerByUsername(req.params.username);if(!streamer)return res.status(404).send("Streamer not found");res.send(commandsPage(streamer))}catch(e){next(e)}});
app.post("/api/regenerate-key",requireStreamer,async(req,res,next)=>{try{const old=req.streamer.overlayKey;await replaceOverlayKey(req.streamer);const set=rooms.get(old);if(set){for(const ws of set)ws.close(4001,"Overlay URL changed");rooms.delete(old)}res.redirect("/dashboard?key=changed")}catch(e){next(e)}});
app.post("/api/test/:kind",requireStreamer,(req,res)=>{const key=req.streamer.overlayKey,name=req.streamer.displayName,tests={wolf:()=>send(key,{type:"chat",username:"TestWolf"+Math.floor(Math.random()*99),message:""}),pack:()=>Array.from({length:5},(_,i)=>setTimeout(()=>send(key,{type:"chat",username:`TestWolf${i+1}`,message:""}),i*350)),moon:()=>send(key,{type:"moon",username:name,detail:"TEST GIFT",force:"purple"}),boss:()=>send(key,{type:"boss",hp:180,duration:60000,test:true}),squirrel:()=>send(key,{type:"squirrel",duration:15000,test:true}),skunk:()=>send(key,{type:"skunk",duration:15000,test:true}),pvp:()=>{send(key,{type:"chat",username:name,message:""});setTimeout(()=>send(key,{type:"chat",username:name,message:"!testpvp"}),2600)}};const run=tests[req.params.kind];if(!run)return res.sendStatus(404);run();res.sendStatus(204)});
app.use("/api/progress",express.json({limit:"4mb"}));
app.put("/api/progress/:key",async(req,res,next)=>{try{const streamer=await getStreamerByKey(req.params.key);if(!streamer)return res.sendStatus(404);if(!req.body||typeof req.body!=="object"||Array.isArray(req.body))return res.sendStatus(400);await saveViewerProgress(streamer.kickUserId,req.body);res.sendStatus(204)}catch(e){next(e)}});
app.get("/overlay/:key",async(req,res,next)=>{try{const streamer=await getStreamerByKey(req.params.key);if(!streamer)return res.status(404).send("This Cyber Pack overlay URL is not active.");const progress=await getProgress(streamer.kickUserId),html=await readFile(new URL("./public/index.html",import.meta.url),"utf8"),config={owner:streamer.username,ownerDisplay:streamer.displayName,overlayKey:streamer.overlayKey,progress,progressEndpoint:`/api/progress/${streamer.overlayKey}`},configured=html.replace('OWNER="lestarwolf"','OWNER=window.__PACK_CONFIG__.owner').replace('STORE_KEY="lestarwolf-pack-progress-v1"','STORE_KEY="lestarwolf-pack-progress-v1-"+window.__PACK_CONFIG__.overlayKey').replace("<script>",`<script>window.__PACK_CONFIG__=${jsonForHtml(config)};</script><script>`);res.type("html").send(configured)}catch(e){next(e)}});
app.use("/overlay",express.static("public",{etag:true,maxAge:"1h"}));
app.get("/test",(_,res)=>{send("legacy",{type:"chat",username:"TestWolf"+Math.floor(Math.random()*99)});res.send("V3 test wolf sent. Check the legacy overlay.")});

app.post("/webhook",express.raw({type:"*/*",limit:"2mb"}),async(req,res)=>{const raw=req.body.toString();try{if(!verifyWebhook(req,raw))return res.sendStatus(401);if(!await markMessage(req.get("Kick-Event-Message-Id")))return res.sendStatus(204);const type=req.get("Kick-Event-Type"),d=JSON.parse(raw),broadcaster=d.broadcaster||{},streamer=await getStreamerById(broadcaster.user_id),key=streamer?.overlayKey||(normalize(broadcaster.username)===LEGACY_OWNER?"legacy":"");if(!key)return res.sendStatus(204);const r=runtime(key),avatarOf=u=>{const p=u?.profile_picture||u?.profile_picture_url||"";return typeof p==="string"?p:typeof p?.url==="string"?p.url:""};if(type==="livestream.status.updated")setLive(key,d.is_live);else if(type==="chat.message.sent"){setLive(key,true);const s=d.sender||{},message=d.content||"",command=String(message).trim().toLowerCase().split(/\s+/)[0],owner=String(s.user_id||"")===String(broadcaster.user_id||"")||normalize(s.username)===normalize(broadcaster.username);if(owner&&(command==="!testboss"||command==="!boss")){r.squirrelUntil=r.skunkUntil=0;send(key,{type:"squirrelStop"});send(key,{type:"skunkStop"});r.bossUntil=Date.now()+60000;send(key,{type:"boss",hp:180,duration:60000,test:true})}else if(owner&&command==="!testsquirrel"){r.bossUntil=r.skunkUntil=0;send(key,{type:"bossStop"});send(key,{type:"skunkStop"});r.squirrelUntil=Date.now()+SQUIRREL_DURATION;send(key,{type:"squirrel",duration:SQUIRREL_DURATION,test:true})}else if(owner&&command==="!testskunk"){r.bossUntil=r.squirrelUntil=0;send(key,{type:"bossStop"});send(key,{type:"squirrelStop"});r.skunkUntil=Date.now()+SKUNK_DURATION;send(key,{type:"skunk",duration:SKUNK_DURATION,test:true})}if(s.username)send(key,{type:"chat",username:s.username,avatar:avatarOf(s),message})}else if(type==="kicks.gifted"&&Number(d.gift?.amount||d.amount||0)>=10){send(key,{type:"moon",username:d.sender?.username||d.gifter?.username||"PACK MEMBER",avatar:avatarOf(d.sender||d.gifter),detail:`${Number(d.gift?.amount||d.amount)} KICKS GIFTED`})}else if(type==="channel.subscription.gifts"){const count=Array.isArray(d.giftees)?d.giftees.length:1;send(key,{type:"moon",username:d.gifter?.username||"ANONYMOUS PACK MEMBER",avatar:avatarOf(d.gifter),detail:`${count} GIFTED SUB${count===1?"":"S"}`})}else if(type==="channel.subscription.new"||type==="channel.subscription.renewal"){const who=d.subscriber||{};send(key,{type:"moon",username:who.username||"PACK MEMBER",avatar:avatarOf(who),detail:type==="channel.subscription.new"?"NEW SUB":"SUB RENEWAL"})}res.sendStatus(204)}catch(e){console.error("Webhook error",e);res.sendStatus(400)}});

wss.on("connection",(ws,req)=>{try{const url=new URL(req.url,"http://localhost");if(url.pathname!=="/live")return ws.close(1008,"Invalid endpoint");const key=url.searchParams.get("key")||"legacy";roomClients(key).add(ws);ws.on("close",()=>{const set=rooms.get(key);if(!set)return;set.delete(ws);if(!set.size)rooms.delete(key)})}catch{ws.close(1008,"Invalid connection")}});
app.use((err,req,res,next)=>{console.error(err);res.status(500).send(`Cyber Pack error: ${safe(err.message||"Unknown error")}`)});

await initDb();
if(process.env.DEV_STREAMER){
  const username=normalize(process.env.DEV_STREAMER);
  await saveStreamer({kickUserId:"dev-streamer",username,displayName:process.env.DEV_STREAMER,avatarUrl:"",overlayKey:process.env.DEV_OVERLAY_KEY||"dev-overlay-key",accessTokenEnc:"",refreshTokenEnc:"",tokenExpiresAt:0,subscriptionData:{development:true}});
}
server.listen(PORT,"0.0.0.0",()=>console.log(`Cyber Pack V4 running on 0.0.0.0:${PORT}${pool?" with PostgreSQL":" in development memory mode"}`));
